name: Test

on:
  push:
    paths-ignore:
      - 'docs/**'
    branches:
      - main
      - 'release**'
  pull_request:
    branches:
      - main
      - 'release**'
    paths-ignore:
      - 'docs/**'
    types: [opened, synchronize]

  # Allows workflows to be manually triggered
  workflow_dispatch:

concurrency:
  group: ${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  # This is used in addition to pre-commit.ci so that we can fail the build
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - id: Changed-files
        uses: tj-actions/changed-files@v35.9.0
      - name: List changed files
        run: echo '${{ steps.changed-files.outputs.all_changed_files }}'
      - uses: pre-commit/action@v3.0.0
        with:
          extra_args: --files ${{ steps.changed-files.outputs.all_changed_files }}
      - name: Check for missing init files
        run: build_tools/fail_on_missing_init_files.sh
        shell: bash

  run-tests:
    needs: code-quality
    name: Test ${{ matrix.os }}-${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
        fail-fast: true
        matrix:
          os: [ubuntu-latest, windows-latest, macOS-latest]
          python-version: ['3.8', '3.9', '3.10', '3.11']
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -VV
          python -m pip install --upgrade pip
          python -m pip install .[test]

      # Commented out for now. Turn on once dependencies are shrunk.
      # - name: Run Safety security check
      #   shell: bash -l {0}
        # This will scan the installed python environment for all installed dependencies
        # including transitive dependencies. Checks for dependencies with known CVEs
        # Ignoring CVEs disputed by NumPy devs with IDs 44715, 44716, 44717
        # run: safety check --full-report -i 44715 -i 44716 -i 44717
        # Do not continue on error. Fail the action if safety returns a
        # non-zero exit code indicating a vulnerability has been found
      #   continue-on-error: false

      - name: Generate Pytest coverage report
        shell: bash -l {0}
        run: |
          python -m pytest

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
